# .pre-commit-config.yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0 # this is optional, use `pre-commit autoupdate` to get the latest rev!
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/jeffpignataro/pre-commit-golang
    rev: v1.0.0
    hooks:
      - id: bazel-buildifier
        name: "bazel buildifier"
        entry: hooks\run-bazel-buildifier.sh
        files: "BUILD.bazel|BUILD"
        language: "script"
        description: "Runs `buildifier`, requires bazel buildifier"
      - id: go-imports
        name: "go imports"
        entry: hooks\run-go-imports.sh
        files: '\.go$'
        language: "script"
        description: "Runs `go imports`, requires golang"
      - id: go-critic
        name: "go-critic"
        entry: hooks\run-go-critic.sh
        files: '\.go$'
        language: "script"
        description: "Runs `go-critic`, requires go-critic"
      - id: golangci-lint
        name: "golangci-lint"
        entry: hooks\run-golangci-lint.sh
        files: '\.go$'
        language: "script"
        description: "Runs `golangci-lint`, requires golangci-lint"
      - id: golangci-lint-conf
        name: "golangci-lint-conf"
        entry: hooks\run-golangci-lint-conf.sh
        files: '\.go$'
        language: "script"
        description: "Runs `golangci-lint` read local config file, requires golangci-lint"
      - id: go-mod-tidy
        name: "go mod tidy"
        entry: hooks\run-go-mod-tidy.sh
        files: '\.go$'
        language: "script"
        description: "Runs `go mod tidy` make sure latest and avaliable go mod file"
