# .pre-commit-config.yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0 # this is optional, use `pre-commit autoupdate` to get the latest rev!
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/jeffpignataro/pre-commit-golang
    rev: v1.1.1
    hooks:
      - id: bazel-buildifier
      - id: go-imports
      - id: go-mod-tidy
      - id: bazel-gazelle
