name: Build CLI Demo
on:
  pull_request:
    branches:
      - "main"
    paths:
      - .github/workflows/cli-demo*
      - cmd/cli-demo
      - pkg
  push:
    branches:
      - "main"
    paths:
      - .github/workflows/cli-demo*
      - cmd/cli-demo
      - pkg
  workflow_dispatch:
jobs:
  bazel-build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ./

    steps:
      - uses: actions/checkout@v3
      - uses: bazelbuild/setup-bazelisk@v2
      - name: Mount bazel cache
        uses: actions/cache@v3
        with:
          path: "~/.cache/bazel"
          key: Cli-Demo-Cache
      - name: Test
        run: bazel query "tests(//...)" | xargs -I {} bazel test
      - name: Build
        if: success()
        run: bazel build //...
      - name: Store artifacts
        uses: actions/upload-artifact@v3
        with:
          name: upload-binary
          path: |
            ./bazel-out/k8-fastbuild/bin/cmd/cli-demo/cli-demo_/cli-demo
          retention-days: 1
