name: Release CLI demo
on:
  workflow_run:
    workflows:
      - "Build CLI Demo"
    types:
      - "completed"
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ./

    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
