name: Deploy Infrastructure

on:
  push:
    branches:
      - main
    paths:
      - "iac/terraform/*"
      - ".github/workflows/terraform*"
  workflow_dispatch:

defaults:
  run:
    working-directory: "iac/terraform"

jobs:
  apply:
    name: Plan and Apply
    runs-on: ubuntu-latest
    environment: personal-aws
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3

      - name: Init
        run: terraform init

      - name: Plan
        run: terraform plan

      - name: Apply
        run: terraform apply
