name: Plan and Validate Infrastructure

on:
  pull_request:
    branches:
      - main
    paths:
      - "iac/terraform/*"
      - ".github/workflows/terraform*"

defaults:
  run:
    working-directory: "iac/terraform"

jobs:
  validate-and-plan:
    name: Validate and Speculative Plan
    runs-on: ubuntu-latest
    environment: personal-aws
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3

      - name: Init
        run: terraform init

      - name: Validate
        run: terraform validate

      - name: Plan
        run: terraform plan
